//
// Created by FATCAT.STARK on 2021/10/4.
//

#ifndef PLACE_RECOGNIZATION_SPATIAL_CALCULATION_H
#define PLACE_RECOGNIZATION_SPATIAL_CALCULATION_H

#endif //PLACE_RECOGNIZATION_SPATIAL_CALCULATION_H
